FROM gradle:8-jdk17 as builder

WORKDIR /app

# Kopiowanie plików zależności Gradle
COPY gradle /app/gradle
COPY build.gradle /app/
COPY settings.gradle /app/

# Pobranie zależności (Gradle będzie je przechowywał w cache)
RUN gradle build --no-daemon

# Kopiowanie całego kodu źródłowego
COPY . .

# Budowanie aplikacji
RUN gradle build --no-daemon

# Etap 2: Aplikacja
FROM amazoncorretto:17
# Ustawienie zmiennych środowiskowych
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH=$PATH:$JAVA_HOME/bin

# Praca w katalogu /app
WORKDIR /app

# Kopiowanie zbudowanego JAR-a z poprzedniego etapu
COPY --from=builder /app/build/libs/coders-0.0.1-SNAPSHOT.jar /app/coders-0.0.1-SNAPSHOT.jar

# Uruchamianie aplikacji
CMD java -jar /app/coders-0.0.1-SNAPSHOT.jar

# Eksponowanie portu 8080
EXPOSE 8080

