# Użyj oficjalnego obrazu Postgres
FROM postgres:16-alpine

# Ustaw zmienne środowiskowe (możesz je także nadpisać w Docker Compose)
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=coders_space

# Skopiuj plik init.sql do katalogu inicjalizacyjnego Postgres
COPY init.sql /docker-entrypoint-initdb.d/

# Expose domyślny port Postgres
EXPOSE 5432
