# Etap 1: Builder - Budowanie aplikacji Angular
FROM --platform=$BUILDPLATFORM node:18 as builder

# Tworzenie katalogu roboczego
WORKDIR /app

# Instalowanie globalnie Angular CLI
RUN npm install -g @angular/cli@17

# Kopiowanie package.json i package-lock.json w celu zainstalowania zależności
COPY package.json package-lock.json ./
RUN npm ci --prefer-offline --no-audit --progress=false

# Kopiowanie reszty aplikacji
COPY . .

# Budowanie aplikacji Angular w trybie produkcyjnym
RUN ng build --configuration production

# Etap 2: Produkcyjny - Uruchamianie aplikacji Angular
FROM nginx:alpine as production

# Usuwanie domyślnej strony Nginx
RUN rm -rf /usr/share/nginx/html/*

# Kopiowanie zbudowanej aplikacji Angular do folderu Nginx
COPY --from=builder /app/dist/coders-space-frontend/browser /usr/share/nginx/html

# Eksponowanie portu, na którym działa aplikacja
EXPOSE 80

# Uruchomienie Nginx
CMD ["nginx", "-g", "daemon off;"]
